# 웹 서버(tomcat) 설정
server:
  servlet:
    context-path: /test
  forward-headers-strategy: FRAMEWORK
  tomcat:
    accesslog:
      enabled: false

# 테스트용 데이터베이스 설정 (H2 Database 사용 예시)
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379