# 웹 서버(tomcat) 설정
server:
  port: 8181
  servlet:
    context-path: /dev
  forward-headers-strategy: FRAMEWORK
  tomcat:
    accesslog:
      enabled: true


# 스프링 모듈 및 기능에 대한 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stim?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  devtools:
    livereload:
      enabled: true


# 환경 설정 변수
jwt:
  secret: 시크릿키설정필요
  expiration: 180000 # ms 3분 (30 * 60 * 1000)


cookie:
  expiration: 180 # 3분


twilio:
  account-sid: YOUR_TWILIO_ACCOUNT_SID
  auth-token: YOUR_TWILIO_AUTH_TOKEN
  phone-number: YOUR_TWILIO_PHONE_NUMBER